# @package _global_

env:
  _target_: gr00t.rl.envs.base_task.base_task.BaseTask
  _recursive_: False
  config:
    experiment_name: ${experiment_name}
    num_envs: ${num_envs}
    headless: ${headless}
    simulator: ${simulator}
    save_rendering_dir: null
    eval_rendering:
      camera_mode: door_top_down
      camera_eye: [-2.5, -2.5, 2.2]
      camera_lookat: [-0.5, 0.0, 0.45]
      fps: 20
      write_initial_frame: true
      write_terminal_frame: true
      additional_cameras:
        - name: handle_top
          camera_mode: handle_top_down
          camera_eye: [0.0, 0.0, 0.65]
          camera_lookat: [0.0, 0.0, 0.0]
        - name: handle_side
          camera_mode: handle_side
          camera_eye: [0.0, 0.62, 0.02]
          camera_lookat: [0.0, 0.0, 0.0]
        - name: door_front_pos_x
          camera_mode: door_top_down
          camera_eye: [4.5, 0.0, 1.025]
          camera_lookat: [0.0, 0.0, 1.025]
        - name: door_front_neg_x
          camera_mode: door_top_down
          camera_eye: [-4.5, 0.0, 1.025]
          camera_lookat: [0.0, 0.0, 1.025]
    experiment_dir: null
    ckpt_dir: null

# Globally accessible parameters
log_task_name: base_task
