#!/usr/bin/env bash
set -euo pipefail
repo=/home/baoquanc/workspace/DoorDog-A2_Piper;py=/usr/bin/python3;isaac=/home/baoquanc/anaconda3/envs/isaaclab/bin/python;supervisor="$repo/.ai/scripts/run_supervisor.py";run_id=v26_5_wave2_r1_policy_residual_20260831_r15;stage="$repo/logs_eval/base_v26/$run_id";static="$stage/M/static";registry="$static/command_registry.json";selectors="$static/selectors";eval_root="$stage/eval";train_root="$repo/logs_rl/by_batch/base_v26/$run_id";logs="$repo/scriptsFORhuman/v26_5/runtime_logs/$run_id"
usage(){ echo "usage: $0 preregister | pilot --launch | pilot-reduce | k1-cell K1_S0|K1_S1 --launch | k1-reduce | formal-admission | smoke --launch | train-cell R15_S0|R15_S1 --launch | eval-cell R15_S0|R15_S1 125|250 --launch | eval-reduce" >&2; }
verify(){ "$py" "$repo/scriptsFORhuman/v26_5/v26_5_wave2_r1_r15_verify.py" --registry "$registry" --selector-root "$selectors"; }
idle(){ local g=$1 uuid;uuid=$(nvidia-smi --query-gpu=index,uuid --format=csv,noheader|awk -F ', ' -v g="$g" '$1==g{print $2}');[[ -n "$uuid" ]]&&! nvidia-smi --query-compute-apps=gpu_uuid,pid --format=csv,noheader|grep -Fq "$uuid"; }
launch(){ local n=$1 g=$2 c=$3 o=$4 checkpoint=$5;r=$("$py" "$supervisor" prepare --name "$n" --session "$n" --cwd "$repo" --command "$c" --output "$o" --checkpoint "$checkpoint" --resource "GPU$g" --resource "IsaacSim_GPU$g");"$py" "$supervisor" launch --receipt "$r"; }
require_pass(){ "$py" - "$repo/.ai/runtime/runs/$1/RUN_RECEIPT.json" <<'PY'
import json,sys
v=json.load(open(sys.argv[1]));
if v.get('state')!='PASS' or v.get('process_returncode')!=0:raise SystemExit('required supervisor receipt is not PASS')
PY
}
case ${1:-} in
 preregister) [[ $# -eq 1 && ! -e "$static" ]]||exit 2;"$py" "$repo/scriptsFORhuman/v26_5/v26_5_wave2_r1_r15_registry.py" --output "$registry";"$py" "$repo/scriptsFORhuman/v26_5/v26_5_wave2_r1_r15_compose.py" --output-dir "$selectors";verify;;
 pilot) [[ $# -eq 2 && $2 == --launch ]]||{ usage;exit 2;};verify;idle 4||exit 1;root="$eval_root/pilot";[[ ! -e "$root" ]]||exit 1;printf -v c '%q ' bash "$repo/scriptsFORhuman/v26_5/v26_5_wave2_r1_r15_pilot_cell.sh" 4 PILOT_S0 "$root" 0;launch "${run_id}_pilot" 4 "$c" "$logs/pilot.log" "$root/dual/PILOT_S0/left/metrics_eval.json";;
 pilot-reduce) [[ $# -eq 1 ]]||exit 2;verify;require_pass "${run_id}_pilot";exec "$isaac" "$repo/scriptsFORhuman/v26_5/v26_5_wave2_r1_r15_reduce.py" --mode pilot --control "$eval_root/pilot/control/PILOT_S0/left" --dual "$eval_root/pilot/dual/PILOT_S0/left" --output "$stage/pilot/reducer.json";;
 k1-cell) [[ $# -eq 3 && $3 == --launch ]]||exit 2;verify;require_pass "${run_id}_pilot";"$py" "$repo/scriptsFORhuman/v26_5/v26_5_wave2_r1_r15_pilot_gate.py" --reducer "$stage/pilot/reducer.json";label=$2;case "$label" in K1_S0)gpu=4;seed=0;delay=0;;K1_S1)gpu=5;seed=1;delay=600;;*)exit 2;;esac;root="$eval_root/K1";[[ ! -e "$root/control/$label" && ! -e "$root/dual/$label" ]]||exit 1;idle "$gpu"||exit 1;printf -v c '%q ' bash "$repo/scriptsFORhuman/v26_5/v26_5_wave2_r1_r15_k1_cell.sh" "$gpu" "$label" "$root" "$seed";[[ $delay == 0 ]]||c="sleep 600; $c";launch "${run_id}_${label,,}" "$gpu" "$c" "$logs/k1/$label.log" "$root/dual/$label/right/metrics_eval.json";;
 k1-reduce) [[ $# -eq 1 ]]||exit 2;verify;require_pass "${run_id}_k1_s0";require_pass "${run_id}_k1_s1";exec "$isaac" "$repo/scriptsFORhuman/v26_5/v26_5_wave2_r1_r15_reduce.py" --mode k1 --root "$eval_root/K1" --output "$stage/K1/identity_reducer.json";;
 formal-admission) [[ $# -eq 1 ]]||exit 2;verify;exec "$py" "$repo/scriptsFORhuman/v26_5/v26_5_wave2_r1_r15_formal_gate.py" --reducer "$stage/K1/identity_reducer.json";;
 smoke) [[ $# -eq 2 && $2 == --launch ]]||exit 2;verify;"$py" "$repo/scriptsFORhuman/v26_5/v26_5_wave2_r1_r15_formal_gate.py" --reducer "$stage/K1/identity_reducer.json";out="$train_root/smoke/R15_SMOKE64_B1";[[ ! -e "$out" ]]||exit 1;idle 4||exit 1;printf -v c '%q ' bash "$repo/scriptsFORhuman/v26_5/v26_5_wave2_r1_r15_smoke.sh" 4 "$out";launch "${run_id}_smoke" 4 "$c" "$logs/smoke.log" "$out/model_step_000001.pt";;
 train-cell) [[ $# -eq 3 && $3 == --launch ]]||exit 2;verify;"$py" "$repo/scriptsFORhuman/v26_5/v26_5_wave2_r1_r15_formal_gate.py" --reducer "$stage/K1/identity_reducer.json";require_pass "${run_id}_smoke";label=$2;case "$label" in R15_S0)gpu=4;;R15_S1)gpu=5;;*)exit 2;;esac;out="$train_root/train/$label";[[ ! -e "$out" ]]||exit 1;idle "$gpu"||exit 1;printf -v c '%q ' bash "$repo/scriptsFORhuman/v26_5/v26_5_wave2_r1_r15_train_cell.sh" "$gpu" "$label" "$out";launch "${run_id}_train_${label,,}" "$gpu" "$c" "$logs/train/$label.log" "$out/model_step_000250.pt";;
 eval-cell) [[ $# -eq 4 && $4 == --launch ]]||exit 2;verify;"$py" "$repo/scriptsFORhuman/v26_5/v26_5_wave2_r1_r15_formal_gate.py" --reducer "$stage/K1/identity_reducer.json";label=$2;step=$3;case "$label" in R15_S0)gpu=4;seed=0;;R15_S1)gpu=5;seed=1;;*)exit 2;;esac;require_pass "${run_id}_train_${label,,}";[[ "$step" =~ ^(125|250)$ ]]||exit 2;checkpoint="$train_root/train/$label/model_step_000${step}.pt";out="$stage/formal_eval";[[ -f "$checkpoint" && ! -e "$out/${label}_STEP0${step}" ]]||exit 1;idle "$gpu"||exit 1;printf -v c '%q ' bash "$repo/scriptsFORhuman/v26_5/v26_5_wave2_r1_r15_formal_eval_cell.sh" "$gpu" "$label" "$step" "$checkpoint" "$out" "$seed";launch "${run_id}_eval_${label,,}_${step}" "$gpu" "$c" "$logs/eval/${label}_${step}.log" "$out/${label}_STEP0${step}/right/metrics_eval.json";;
 eval-reduce) [[ $# -eq 1 ]]||exit 2;verify;for cell in r15_s0 r15_s1;do for step in 125 250;do require_pass "${run_id}_eval_${cell}_${step}";done;done;exec "$isaac" "$repo/scriptsFORhuman/v26_5/v26_5_wave2_r1_r15_reduce.py" --mode formal --root "$stage/formal_eval" --train-root "$train_root" --output "$stage/formal_eval/reducer.json";;
 *)usage;exit 2;;
esac
